# Nome da nossa automação
name: Update Firmware Version Badge

on:
  # Aciona a automação em qualquer push para a branch 'main'
  push:
    branches:
      - main

# Adiciona a permissão de escrita para o bot poder fazer o commit
permissions:
  contents: write

jobs:
  update-badge:
    # Sintaxe do 'if' corrigida para o padrão do GitHub Actions.
    # Ele agora checa se a mensagem NÃO contém 'Bot:'.
    if: "${{ !contains(github.event.head_commit.message, 'Bot:') }}"

    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Acha a última versão de firmware no index.html
      - name: Get latest firmware version
        id: get_version
        run: |
          # ATUALIZADO: Agora ele primeiro remove as entradas comentadas (//) e DEPOIS procura pela última versão.
          LATEST_VERSION=$(grep -v "^ *//" index.html | grep -o "version: *'[^']*'" | tail -n 1 | sed "s/version: *'//;s/'$//")
          
          # Se não encontrar nenhuma versão, usa um valor padrão
          if [ -z "$LATEST_VERSION" ]; then
            LATEST_VERSION="not-found"
          fi
          
          echo "Found version: $LATEST_VERSION"
          # O site shields.io usa '--' para representar um '-', então a gente substitui
          BADGE_VERSION=$(echo $LATEST_VERSION | sed 's/-/--/g')
          echo "Badge version: $BADGE_VERSION"
          # Salva a versão para usar no próximo passo
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "badge_version=$BADGE_VERSION" >> $GITHUB_OUTPUT

      # 3. Atualiza o 'atualizar_jade_wallet.md' com a nova versão
      - name: Update atualizar_jade_wallet.md
        run: |
          # Usa o 'sed' para encontrar a linha do badge e substituir a versão no arquivo correto
          sed -i "s|img.shields.io/badge/Firmware-.*-blue|img.shields.io/badge/Firmware-${{ steps.get_version.outputs.badge_version }}-blue|g" atualizar_jade_wallet.md

      # 4. Faz o commit e push das mudanças no 'atualizar_jade_wallet.md'
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem de commit agora bate com a regra do 'if'
          commit_message: "Bot: Auto-update firmware badge to v${{ steps.get_version.outputs.version }}"
          branch: main
          # O padrão de arquivo a ser verificado para commit
          file_pattern: atualizar_jade_wallet.md
